#!/bin/bash
set -e

if [ "$#" -ne 1 ]; then
    echo "Usage: bash $0 ROM_DIR"
    exit 1
fi

ROM_DIR=$1

# Debloat Product.
rm -rf "$ROM_DIR/product/app/BardShell"
rm -rf "$ROM_DIR/product/app/Duo"
rm -rf "$ROM_DIR/product/app/DuoStub"
rm -rf "$ROM_DIR/product/app/GoogleCalendarSyncAdapter"
rm -rf "$ROM_DIR/product/app/Photos"
rm -rf "$ROM_DIR/product/priv-app/AndroidAuto"
rm -rf "$ROM_DIR/product/priv-app/AndroidAutoStub"
rm -rf "$ROM_DIR/product/priv-app/AndroidSystemIntelligence"
rm -rf "$ROM_DIR/product/priv-app/GoogleRestore"
rm -rf "$ROM_DIR/product/priv-app/Messages"
rm -rf "$ROM_DIR/product/priv-app/SearchSelector"

# De-odex Product.
rm -rf "$ROM_DIR/product/app/BardShell/oat"
rm -rf "$ROM_DIR/product/app/Gmail2/oat"
rm -rf "$ROM_DIR/product/app/Maps/oat"
rm -rf "$ROM_DIR/product/app/SpeechServicesByGoogle/oat"
rm -rf "$ROM_DIR/product/app/YouTube/oat"
rm -rf "$ROM_DIR/product/priv-app/Velvet/oat"

# Debloating System app.
rm -rf "$ROM_DIR/system/system/app/AirGlance"
rm -rf "$ROM_DIR/system/system/app/AirReadingGlass"
rm -rf "$ROM_DIR/system/system/app/ARCore"
rm -rf "$ROM_DIR/system/system/app/ARDrawing"
rm -rf "$ROM_DIR/system/system/app/ARZone"
rm -rf "$ROM_DIR/system/system/app/BGMProvider"
rm -rf "$ROM_DIR/system/system/app/BixbyWakeup"
rm -rf "$ROM_DIR/system/system/app/BlockchainBasicKit"
rm -rf "$ROM_DIR/system/system/app/Cameralyzer"
rm -rf "$ROM_DIR/system/system/app/DictDiotekForSec"
rm -rf "$ROM_DIR/system/system/app/EasymodeContactsWidget81"
rm -rf "$ROM_DIR/system/system/app/Fast"
rm -rf "$ROM_DIR/system/system/app/FBAppManager_NS"
rm -rf "$ROM_DIR/system/system/app/FunModeSDK"
rm -rf "$ROM_DIR/system/system/app/GearManagerStub"
rm -rf "$ROM_DIR/system/system/app/KidsHome_Installer"
rm -rf "$ROM_DIR/system/system/app/LinkSharing_v11"
rm -rf "$ROM_DIR/system/system/app/LiveDrawing"
rm -rf "$ROM_DIR/system/system/app/MAPSAgent"
rm -rf "$ROM_DIR/system/system/app/MdecService"
rm -rf "$ROM_DIR/system/system/app/MinusOnePage"
rm -rf "$ROM_DIR/system/system/app/MoccaMobile"
rm -rf "$ROM_DIR/system/system/app/Netflix_stub"
rm -rf "$ROM_DIR/system/system/app/Notes40"
rm -rf "$ROM_DIR/system/system/app/ParentalCare"
rm -rf "$ROM_DIR/system/system/app/PhotoTable"
rm -rf "$ROM_DIR/system/system/app/PlayAutoInstallConfig"
rm -rf "$ROM_DIR/system/system/app/SamsungPassAutofill_v1"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_de_DE_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_el_GR_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_en_GB_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_en_US_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_en_US_l03"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_es_ES_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_es_MX_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_es_US_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_fr_FR_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_hi_IN_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_it_IT_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_pl_PL_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_pt_BR_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_ru_RU_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_th_TH_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_vi_VN_f00"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_en_IN_f00"
rm -rf "$ROM_DIR/system/system/app/SmartReminder"
rm -rf "$ROM_DIR/system/system/app/SmartSwitchStub"
rm -rf "$ROM_DIR/system/system/app/UniversalMDMClient"
rm -rf "$ROM_DIR/system/system/app/VideoEditorLite_Dream_N"
rm -rf "$ROM_DIR/system/system/app/VisionIntelligence3.7"
rm -rf "$ROM_DIR/system/system/app/VoiceAccess"
rm -rf "$ROM_DIR/system/system/app/VTCameraSetting"
rm -rf "$ROM_DIR/system/system/app/WebManual"
rm -rf "$ROM_DIR/system/system/app/WifiGuider"
rm -rf "$ROM_DIR/system/system/app/KTAuth"
rm -rf "$ROM_DIR/system/system/app/KTCustomerService"
rm -rf "$ROM_DIR/system/system/app/KTUsimManager"
rm -rf "$ROM_DIR/system/system/app/LGUMiniCustomerCenter"
rm -rf "$ROM_DIR/system/system/app/LGUplusTsmProxy"
rm -rf "$ROM_DIR/system/system/app/SamsungTTSVoice_ko_KR_r00"
rm -rf "$ROM_DIR/system/system/app/SketchBook"
rm -rf "$ROM_DIR/system/system/app/SKTMemberShip_new"
rm -rf "$ROM_DIR/system/system/app/SktUsimService"
rm -rf "$ROM_DIR/system/system/app/TWorld"

# Debloat System priv-app.
rm -rf "$ROM_DIR/system/system/priv-app/AirCommand"
rm -rf "$ROM_DIR/system/system/priv-app/AppUpdateCenter"
rm -rf "$ROM_DIR/system/system/priv-app/AREmoji"
rm -rf "$ROM_DIR/system/system/priv-app/AREmojiEditor"
rm -rf "$ROM_DIR/system/system/priv-app/AuthFramework"
rm -rf "$ROM_DIR/system/system/priv-app/AutoDoodle"
rm -rf "$ROM_DIR/system/system/priv-app/AvatarEmojiSticker"
rm -rf "$ROM_DIR/system/system/priv-app/AvatarEmojiSticker_S"
rm -rf "$ROM_DIR/system/system/priv-app/Bixby"
rm -rf "$ROM_DIR/system/system/priv-app/BixbyInterpreter"
rm -rf "$ROM_DIR/system/system/priv-app/BixbyVisionFramework3.5"
rm -rf "$ROM_DIR/system/system/priv-app/DevGPUDriver-EX2200"
rm -rf "$ROM_DIR/system/system/priv-app/DigitalKey"
rm -rf "$ROM_DIR/system/system/priv-app/Discover"
rm -rf "$ROM_DIR/system/system/priv-app/DiscoverSEP"
rm -rf "$ROM_DIR/system/system/priv-app/EarphoneTypeC"
rm -rf "$ROM_DIR/system/system/priv-app/EasySetup"
rm -rf "$ROM_DIR/system/system/priv-app/FBInstaller_NS"
rm -rf "$ROM_DIR/system/system/priv-app/FBServices"
rm -rf "$ROM_DIR/system/system/priv-app/FotaAgent"
rm -rf "$ROM_DIR/system/system/priv-app/GalleryWidget"
rm -rf "$ROM_DIR/system/system/priv-app/GameDriver-EX2100"
rm -rf "$ROM_DIR/system/system/priv-app/GameDriver-EX2200"
rm -rf "$ROM_DIR/system/system/priv-app/GameDriver-SM8150"
rm -rf "$ROM_DIR/system/system/priv-app/HashTagService"
rm -rf "$ROM_DIR/system/system/priv-app/MultiControlVP6"
rm -rf "$ROM_DIR/system/system/priv-app/LedCoverService"
rm -rf "$ROM_DIR/system/system/priv-app/LinkToWindowsService"
rm -rf "$ROM_DIR/system/system/priv-app/LiveStickers"
rm -rf "$ROM_DIR/system/system/priv-app/MemorySaver_O_Refresh"
rm -rf "$ROM_DIR/system/system/priv-app/MultiControl"
rm -rf "$ROM_DIR/system/system/priv-app/OMCAgent5"
rm -rf "$ROM_DIR/system/system/priv-app/OneDrive_Samsung_v3"
rm -rf "$ROM_DIR/system/system/priv-app/OneStoreService"
rm -rf "$ROM_DIR/system/system/priv-app/SamsungCarKeyFw"
rm -rf "$ROM_DIR/system/system/priv-app/SamsungPass"
rm -rf "$ROM_DIR/system/system/priv-app/SamsungSmartSuggestions"
rm -rf "$ROM_DIR/system/system/priv-app/SettingsBixby"
rm -rf "$ROM_DIR/system/system/priv-app/SetupIndiaServicesTnC"
rm -rf "$ROM_DIR/system/system/priv-app/SKTFindLostPhone"
rm -rf "$ROM_DIR/system/system/priv-app/SKTHiddenMenu"
rm -rf "$ROM_DIR/system/system/priv-app/SKTMemberShip"
rm -rf "$ROM_DIR/system/system/priv-app/SKTOneStore"
rm -rf "$ROM_DIR/system/system/priv-app/SktUsimService"
rm -rf "$ROM_DIR/system/system/priv-app/SmartEye"
rm -rf "$ROM_DIR/system/system/priv-app/SmartPush"
rm -rf "$ROM_DIR/system/system/priv-app/SmartThingsKit"
rm -rf "$ROM_DIR/system/system/priv-app/SmartTouchCall"
rm -rf "$ROM_DIR/system/system/priv-app/SOAgent7"
rm -rf "$ROM_DIR/system/system/priv-app/SOAgent75"
rm -rf "$ROM_DIR/system/system/priv-app/SOAgent76"
rm -rf "$ROM_DIR/system/system/priv-app/SolarAudio-service"
rm -rf "$ROM_DIR/system/system/priv-app/SPPPushClient"
rm -rf "$ROM_DIR/system/system/priv-app/sticker"
rm -rf "$ROM_DIR/system/system/priv-app/StickerFaceARAvatar"
rm -rf "$ROM_DIR/system/system/priv-app/StoryService"
rm -rf "$ROM_DIR/system/system/priv-app/SumeNNService"
rm -rf "$ROM_DIR/system/system/priv-app/SVoiceIME"
rm -rf "$ROM_DIR/system/system/priv-app/SwiftkeyIme"
rm -rf "$ROM_DIR/system/system/priv-app/SwiftkeySetting"
rm -rf "$ROM_DIR/system/system/priv-app/SystemUpdate"
rm -rf "$ROM_DIR/system/system/priv-app/TADownloader"
rm -rf "$ROM_DIR/system/system/priv-app/TalkbackSE"
rm -rf "$ROM_DIR/system/system/priv-app/TaPackAuthFw"
rm -rf "$ROM_DIR/system/system/priv-app/TPhoneOnePackage"
rm -rf "$ROM_DIR/system/system/priv-app/TPhoneSetup"
rm -rf "$ROM_DIR/system/system/priv-app/TWorld"
rm -rf "$ROM_DIR/system/system/priv-app/UltraDataSaving_O"
rm -rf "$ROM_DIR/system/system/priv-app/vexfwk_service"
rm -rf "$ROM_DIR/system/system/priv-app/YourPhone_P1_5"

# Delete unnecessary files and folders.
rm -rf "$ROM_DIR/system/system/etc/init/boot-image.bprof"
rm -rf "$ROM_DIR/system/system/etc/init/boot-image.prof"
rm -rf "$ROM_DIR/system/system/hidden"
rm -rf "$ROM_DIR/system/system/preload"
rm -rf "$ROM_DIR/system/system/tts"
