name: QuantumROM Tools

on:
  workflow_dispatch:
    inputs:
      DEVICE_MODEL:
        description: "Enter the DEVICE_MODEL."
        required: true
        default: "SM-A225F"
      CSC:
        description: "Enter the CSC (Country Specific Code)."
        required: true
        default: "BKD"
      IMEI:
        description: "Enter the device IMEI number."
        required: true
        default: "350167020473859"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Free disk space
        run: |
          # sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          # sudo docker image prune --all --force
          # sudo docker builder prune -a
          
      - name: Installing required packages
        run: |
          chmod +x ./scripts/install_packages.sh
          sudo bash ./scripts/install_packages.sh

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Start ROM download and modify process
        run: |
          chmod +x ./mod_rom_1.sh
          sudo bash ./mod_rom_1.sh "${{ github.event.inputs.DEVICE_MODEL }}" "${{ github.event.inputs.CSC }}" "${{ github.event.inputs.IMEI }}"

      - name: Split files before uploading if need
        run: |
          GIT_SUPPORT_SIZE=2147000000
          OUT_DIR="./out"
          echo "--- Checking for large files in $OUT_DIR ---"

          for file in "$OUT_DIR"/*; do
            [ -f "$file" ] || continue
            FILE_SIZE=$(stat -c%s "$file")
            if [ "$FILE_SIZE" -gt "$GIT_SUPPORT_SIZE" ]; then
              echo "📦 Splitting: $file (Size: $FILE_SIZE bytes)"
              sudo split -b "$GIT_SUPPORT_SIZE" -d -a 3 "$file" "$file.part"
              sudo rm -f "$file"
            fi
          done

      - name: Upload all files to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "build-${{ github.run_id }}"
          name: "QuantumROM Build: ${{ github.run_id }}"
          body: |
            ***Build Information***
            - 📱 Device Model: ${{ github.event.inputs.DEVICE_MODEL }}
            - 🌍 Rom CSC: ${{ github.event.inputs.CSC }}
          files: |
            ./out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Clean everything
        run: |
          sudo rm -rf *
