name: QuantumROM Tools

on:
  workflow_dispatch:
    inputs:
      DEVICE_MODEL:
        description: "Enter the DEVICE_MODEL."
        required: true
        default: "SM-A225F"
      CSC:
        description: "Enter the CSC (Country Specific Code)."
        required: true
        default: "BKD"
      IMEI:
        description: "Enter the device IMEI number."
        required: true
        default: "350167020473859"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Process.
        run: |
          chmod +x ./mod_rom_1.sh
          sudo bash ./mod_rom_1.sh "${{ github.event.inputs.DEVICE_MODEL }}" "${{ github.event.inputs.CSC }}" "${{ github.event.inputs.IMEI }}"

      - name: Uploading all xz file to Release.
        uses: softprops/action-gh-release@v1
        with:
          files: "*.xz"
          name: "${{ env.BUILD_VERSION }}.zip"
          tag_name: "${{ github.run_id }}"
          body: |
            DEVICE_MODEL: ${{ env.DEVICE_MODEL }}
            CSC: ${{ env.ANDROID_VERSION }}
            img files size:
            ${{ env.IMG_INFO }}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
