name: QuantumROM Tools

on:
  workflow_dispatch:
    inputs:
      STOCK_DEVICE_MODEL:
        description: "Enter the STOCK_DEVICE_MODEL."
        required: true
        default: "SM-A225F"
      TARGET_DEVICE_MODEL:
        description: "Enter the TARGET_DEVICE_MODEL."
        required: true
        default: "SM-A245F"
      TARGET_DEVICE_CSC:
        description: "Enter the TARGET_DEVICE_CSC (Country Specific Code)."
        required: true
        default: "BKD"
      TARGET_DEVICE_IMEI:
        description: "Ent0er the TARGET_DEVICE_IMEI number."
        required: true
        default: "357181567907875"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
          
      - name: Installing required packages.
        run: |
          chmod +x ./scripts/install_packages.sh
          sudo bash ./scripts/install_packages.sh

      - name: Setup directories.
        run: |
          chmod +x ./scripts/setup_directories.sh
          sudo bash ./scripts/setup_directories.sh fw_download work out

      - name: Starting target device firmware download.
        run: |
          chmod +x ./scripts/download_firmware.sh
          sudo bash ./QuantumROM/Devices/Source_Rom.sh "${{ github.event.inputs.TARGET_DEVICE_MODEL }}" "${{ github.event.inputs.TARGET_DEVICE_CSC }}" "${{ github.event.inputs.TARGET_DEVICE_IMEI }}"

      - name: Starting stock device firmware download.
        run: |
          chmod +x ./QuantumROM/Devices/${{ github.event.inputs.STOCK_DEVICE_MODEL }}/${{ github.event.inputs.STOCK_DEVICE_MODEL }}.sh
          sudo bash ./QuantumROM/Devices/${{ github.event.inputs.STOCK_DEVICE_MODEL }}/${{ github.event.inputs.STOCK_DEVICE_MODEL }}.sh

      - name: Splitting files before uploading if need.
        run: |
          GIT_SUPPORT_SIZE=2147000000
          OUT_DIR="./out"
          echo "--- Checking for large files in $OUT_DIR ---"

          for file in "$OUT_DIR"/*; do
            [ -f "$file" ] || continue
            FILE_SIZE=$(stat -c%s "$file")
            if [ "$FILE_SIZE" -gt "$GIT_SUPPORT_SIZE" ]; then
              echo "📦 Splitting: $file (Size: $FILE_SIZE bytes)"
              sudo split -b "$GIT_SUPPORT_SIZE" -d -a 3 "$file" "$file.part"
              sudo rm -f "$file"
            fi
          done

      - name: Uploading all files to GitHub Release.
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "build-${{ github.run_id }}"
          name: "QuantumROM Build: ${{ github.run_id }}"
          body: |
            ***Build Information***
            - 📱 Device Model: ${{ github.event.inputs.DEVICE_MODEL }}
            - 🌍 Rom CSC: ${{ github.event.inputs.CSC }}
          files: |
            ./out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Cleaning everything.
        run: |
          sudo rm -rf *
