name: QuantumROM Tools

on:
  workflow_dispatch:
    inputs:
      STOCK_DEVICE:
        description: "Enter the STOCK_DEVICE_MODEL."
        required: true
        default: "SM-A225F"
      TARGET_DEVICE:
        description: "Enter the TARGET_DEVICE_MODEL."
        required: true
        default: "SM-A346E"
      TARGET_DEVICE_CSC:
        description: "Enter the TARGET_DEVICE_CSC (Country Specific Code)."
        required: true
        default: "BKD"
      TARGET_DEVICE_IMEI:
        description: "Enter the TARGET_DEVICE_IMEI number."
        required: true
        default: "353435774197736"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installing required packages.
        run: |
          sudo apt install -y p7zip-full lz4 android-sdk-libsparse-utils python3 python3-pip zipalign unzip e2fsprogs
          pip3 install liblp tgcrypto pyrogram
          pip3 install git+https://github.com/martinetd/samloader.git
          # Binary
          chmod +x "$(pwd)/bin/ext4/make_ext4fs"
          chmod +x "$(pwd)/bin/erofs-utils/extract.erofs"
          chmod +x "$(pwd)/bin/erofs-utils/mkfs.erofs"

      - name: Setup directories.
        run: |
          chmod +x ./scripts/setup_directories.sh
          bash ./scripts/setup_directories.sh FIRMWARE WORK OUT

      - name: Make Rom.
        run: |
          chmod +x ./sixteen.sh
          bash ./sixteen.sh ${{ github.event.inputs.STOCK_DEVICE }} ${{ github.event.inputs.TARGET_DEVICE }} ${{ github.event.inputs.TARGET_DEVICE_CSC }} ${{ github.event.inputs.TARGET_DEVICE_IMEI }}

      - name: Splitting files before uploading if need.
        run: |
          GIT_SUPPORT_SIZE=2147483647
          OUT_DIR="./OUT"
          echo "BUILD_TIME=$(date '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV
          echo "--- Checking for large files in $OUT_DIR ---"

          for file in "$OUT_DIR"/*; do
            [ -f "$file" ] || continue
            FILE_SIZE=$(stat -c%s "$file")
            if [ "$FILE_SIZE" -gt "$GIT_SUPPORT_SIZE" ]; then
              echo "📦 Splitting: $file (Size: $FILE_SIZE bytes)"
              split -b "$GIT_SUPPORT_SIZE" -d -a 3 "$file" "$file.part"
              rm -f "$file"
            fi
          done

      - name: Uploading all files to GitHub Release.
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "build-${{ github.run_id }}"
          name: "QuantumROM Build: ${{ github.run_id }}"
          body: |
            ***Build Information***
            - ➡️ Build For: ${{ github.event.inputs.STOCK_DEVICE }}
            - ➡️ Build From: ${{ GITHUB.EVENT.INPUTS.TARGET_DEVICE }}
            - ⏰️ Build Time: ${{ env.BUILD_TIME }}
          files: |
            ./OUT/*
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Cleaning everything.
        run: |
          rm -rf *
