name: QuantumROM Tools Sixteen

on:
  workflow_dispatch:
    inputs:
      STOCK_DEVICE:
        description: "STOCK_DEVICE_MODEL or None"
        required: true
        default: "SM-A225F"

      USE_UI_8_TETHERING_APEX:
        description: "Set True if your kernel BPF version is 5.4 (lower than 5.10)"
        required: true
        default: "False"

      TARGET_DEVICE:
        description: "TARGET_DEVICE_MODEL"
        required: true
        default: "SM-A346E"

      TARGET_DEVICE_CSC:
        description: "TARGET_DEVICE_CSC"
        required: true
        default: "BKD"

      TARGET_DEVICE_IMEI:
        description: "TARGET_DEVICE_IMEI"
        required: true
        default: "353435774197736"

      OUTPUT_FILESYSTEM:
        description: "OUTPUT_FILESYSTEM (erofs/ext4,f2fs)"
        required: true
        default: "erofs"

      COMPRESS_IMG_TO_XZ:
        description: "Compress IMG to XZ (True/False)"
        required: true
        default: "False"

env:
  FIRM_DIR: ${{ github.workspace }}/FW
  WORK_DIR: ${{ github.workspace }}/WORK
  OUT_DIR: ${{ github.workspace }}/OUT
  APKTOOL: ${{ github.workspace }}/bin/java/apktool.jar
  TARGET_DEVICE: ${{ github.event.inputs.TARGET_DEVICE }}
  STOCK_DEVICE: ${{ github.event.inputs.STOCK_DEVICE }}
  OUTPUT_FILESYSTEM: ${{ github.event.inputs.OUTPUT_FILESYSTEM }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  COMPRESS_IMG_TO_XZ: ${{ github.event.inputs.COMPRESS_IMG_TO_XZ }}
  USE_UI_8_TETHERING_APEX: ${{ github.event.inputs.USE_UI_8_TETHERING_APEX }}

jobs:
  build:
    name: Start QuantumROM Tools Sixteen
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate STOCK_DEVICE
        run: |
          DEVICE_PATH="QuantumROM/Devices/$STOCK_DEVICE"

          if [ "$STOCK_DEVICE" != "None" ] && [ ! -d "$DEVICE_PATH" ]; then
            echo "❌ $STOCK_DEVICE is not supported with this tool."
            exit 1
          fi

      - name: Remove unnecessary files
        uses: rokibhasansagar/slimhub_actions@v25.42.5

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y p7zip-full lz4 liblz4-1 liblz4-dev libzstd1 libzstd-dev build-essential android-sdk-libsparse-utils f2fs-tools fuse2fs fuse e2fsprogs python3 python3-pip zipalign unzip openjdk-17-jdk jq perl xxd kmod linux-modules-extra-$(uname -r)
          sudo modprobe f2fs || true
          python3 -m pip install --break-system-packages git+https://github.com/SN-Abdullah-Al-Noman/samloader.git
          mkdir -p "$FIRM_DIR" "$WORK_DIR" "$OUT_DIR"

      - name: Download firmware ▶️ ${{ github.event.inputs.TARGET_DEVICE }} - ${{ github.event.inputs.TARGET_DEVICE_CSC }}
        run: |
          source scripts/QuantumRom.sh
          DOWNLOAD_FIRMWARE "${{ github.event.inputs.TARGET_DEVICE }}" "${{ github.event.inputs.TARGET_DEVICE_CSC }}" "${{ github.event.inputs.TARGET_DEVICE_IMEI }}" "$FIRM_DIR"

      - name: Extract firmware
        run: |
          source scripts/QuantumRom.sh
          EXTRACT_FIRMWARE "$FIRM_DIR/$TARGET_DEVICE"

      - name: Extract super.img
        run: |
          source scripts/QuantumRom.sh
          EXTRACT_SUPER_IMG "$FIRM_DIR/$TARGET_DEVICE"

      - name: Extract partition images
        run: |
          source scripts/QuantumRom.sh
          EXTRACT_FIRMWARE_IMG "$FIRM_DIR/$TARGET_DEVICE" "all"

      - name: Decode OMC
        run: |
          source scripts/QuantumRom.sh
          DECODE_OMC "$FIRM_DIR/$TARGET_DEVICE"

      - name: Debloat ROM
        run: |
          source scripts/debloat.sh
          source scripts/QuantumRom.sh
          DEBLOAT "$FIRM_DIR/$TARGET_DEVICE"

      - name: Apply stock config
        run: |
          source scripts/QuantumRom.sh
          APPLY_STOCK_CONFIG "$FIRM_DIR/$TARGET_DEVICE"

      - name: Patch SELinux
        run: |
          source scripts/QuantumRom.sh
          PATCH_SELINUX "$FIRM_DIR/$TARGET_DEVICE"

      - name: Disable security
        run: |
          source scripts/QuantumRom.sh
          DISABLE_SECURITY "$FIRM_DIR/$TARGET_DEVICE"

      - name: Add flagship apps
        run: |
          source scripts/QuantumRom.sh
          ADD_FLAGSHIP_APPS "$FIRM_DIR/$TARGET_DEVICE"

      - name: Apply custom features
        run: |
          source scripts/QuantumRom.sh
          APPLY_CUSTOM_FEATURES "$FIRM_DIR/$TARGET_DEVICE"

      - name: Decompile framework jars
        run: |
          source scripts/QuantumRom.sh

          INSTALL_FRAMEWORK "$APKTOOL" "$FIRM_DIR/$TARGET_DEVICE/system/system/framework/framework-res.apk"
          DECOMPILE "$APKTOOL" "$FIRM_DIR/$TARGET_DEVICE/system/system/framework" "$FIRM_DIR/$TARGET_DEVICE/system/system/framework/ssrm.jar" "$WORK_DIR"
          DECOMPILE "$APKTOOL" "$FIRM_DIR/$TARGET_DEVICE/system/system/framework" "$FIRM_DIR/$TARGET_DEVICE/system/system/framework/services.jar" "$WORK_DIR"
          DECOMPILE "$APKTOOL" "$FIRM_DIR/$TARGET_DEVICE/system/system/framework" "$FIRM_DIR/$TARGET_DEVICE/system/system/framework/samsungkeystoreutils.jar" "$WORK_DIR"

      - name: Patch framework jars
        run: |
          source scripts/QuantumRom.sh

          PATCH_SSRM "$WORK_DIR/ssrm"
          # PATCH_KNOX_GUARD "$WORK_DIR/services"
          PATCH_FLAG_SECURE "$WORK_DIR/services"
          PATCH_SECURE_FOLDER "$WORK_DIR/services"
          PATCH_PRIVATE_SHARE "$WORK_DIR/samsungkeystoreutils"

      - name: Recompile framework jars
        run: |
          source scripts/QuantumRom.sh

          DECOMPILE_DIR="$FIRM_DIR/$TARGET_DEVICE/system/system/framework"
          RECOMPILE "$APKTOOL" "$DECOMPILE_DIR" "$WORK_DIR/ssrm" "$WORK_DIR"
          RECOMPILE "$APKTOOL" "$DECOMPILE_DIR" "$WORK_DIR/services" "$WORK_DIR"
          RECOMPILE "$APKTOOL" "$DECOMPILE_DIR" "$WORK_DIR/samsungkeystoreutils" "$WORK_DIR"
          mv -f "$WORK_DIR"/*.jar "$DECOMPILE_DIR/" || true

      - name: Patch Bluetooth library
        run: |
          source scripts/QuantumRom.sh
          PATCH_BT_LIB "$FIRM_DIR/$TARGET_DEVICE" "$WORK_DIR"

      - name: Update build.prop
        run: |
          source scripts/QuantumRom.sh
          VERSION="1"
          D_ID="$(grep -m1 '^ro.build.display.id=' "$FIRM_DIR/$TARGET_DEVICE/system/system/build.prop" | cut -d= -f2 | tr -d '\r')"

          BUILD_PROP "$FIRM_DIR/$TARGET_DEVICE" "system" "ro.build.display.id" "${D_ID} V-${VERSION}: Build with Quantum Tools"

      - name: Build partition images
        run: |
          source scripts/QuantumRom.sh
          BUILD_IMG "$FIRM_DIR/$TARGET_DEVICE" "all" "$OUTPUT_FILESYSTEM" "$OUT_DIR"

      - name: Compress all .img & create zip
        run: |
          echo "BUILD_TIME=$(TZ='Asia/Dhaka' date '+%Y-%m-%d %I:%M:%S %p UTC+6')" >> "$GITHUB_ENV"

          ZIP_NAME="${TARGET_DEVICE}_Port_For_${STOCK_DEVICE}.zip"
          ZIP_PATH="$OUT_DIR/$ZIP_NAME"

          if [ "${{ github.event.inputs.COMPRESS_IMG_TO_XZ }}" = "True" ]; then
            echo "Compressing all .img files to .xz..."

            shopt -s nullglob

            for img in "$OUT_DIR"/*.img; do
              echo "Compressing $img"
              sudo xz -9 -T0 "$img"
            done
          fi

          echo "Creating zip: $ZIP_NAME"

          7z a -tzip "$ZIP_PATH" "$OUT_DIR"/* -mx=5

          echo "ZIP_PATH=$ZIP_PATH" >> "$GITHUB_ENV"

      - name: Upload file in GoFile & create release
        run: |
          bash release.sh